### ISSUE TITLE
'calc_scale'  method  isn't equivalent to focal loss，but it may achieve the desired effect of focal loss.Emm

### ISSUE THREAD

**Issue by Atakey** [viplix3/YOLO#10]
https://github.com/viplix3/YOLO/blob/03a2d5043e5c1eb227d59dc47b7b7f49e887021f/utils/yolo_loss.py#L115

'calc_scale'  method  isn't equivalent to focal loss，but it may achieve the desired effect of focal loss.  Emm.

**Comment by viplix3** [comment]
Yeah, I was actually trying to solve a different problem when I implemented this, and I didn't know about the Focal loss back then.
But as it turns out, this is nothing but a special case of focal loss [FL(pt) = −αt(1 − pt)^γ log(pt)] with α = 0.5 and γ = 2
