### ISSUE TITLE
Have you ever try to train the model from cratch without restore any weight?

### ISSUE THREAD

**Issue by Fighting-JJ** [viplix3/YOLO#2]
thank you a lot.

**Comment by viplix3** [comment]
Yes I did, but for a single class.
For muliple classes the classification loss is not coverging as expected, maybe it has to do something with the hyper parameters.
I am experimenting with focal loss and multi-resolution training.
Will push an update once I get better results.

**Comment by Fighting-JJ** [comment]
Thanks for your reply.
